### ISSUE TITLE
`notation` sollte auch andere Formate erlauben als Semver

### ISSUE THREAD

**Issue by mechtelm** [iqb-vocabs/csv2ttl#6]
Manchmal will man eine Liste nicht hierarchisch haben und trotzdem den Einträgen ein sprachunabhängiges Kürzel spendieren. Daher sollte nur beim Semver-Format eine Hierarchie angelegt werden, ansonsten aber auch andere Formate für `notation` zugelassen werden.

**Comment by nanoyan** [comment]
Mann kann Hierarchie mit Nummer angelen(z.B 1, 1.1, 1.2), aber nicht(I, I.1, I.2)
